Attribute VB_Name = "關於阿拉伯數字轉中文數字"
Function noToChineseWord(number)
If (number = 1) Then
    noToChineseWord = "一"
ElseIf (number = 2) Then
    noToChineseWord = "二"
ElseIf (number = 3) Then
    noToChineseWord = "三"
ElseIf (number = 4) Then
    noToChineseWord = "四"
ElseIf (number = 5) Then
    noToChineseWord = "五"
ElseIf (number = 6) Then
    noToChineseWord = "六"
ElseIf (number = 7) Then
    noToChineseWord = "七"
ElseIf (number = 8) Then
    noToChineseWord = "八"
ElseIf (number = 9) Then
    noToChineseWord = "九"
ElseIf (number = 10) Then
    noToChineseWord = "十"
ElseIf (number = 11) Then
    noToChineseWord = "十一"
ElseIf (number = 12) Then
    noToChineseWord = "十二"
ElseIf (number = 13) Then
    noToChineseWord = "十三"
ElseIf (number = 14) Then
    noToChineseWord = "十四"
ElseIf (number = 15) Then
    noToChineseWord = "十五"
ElseIf (number = 16) Then
    noToChineseWord = "十六"
ElseIf (number = 17) Then
    noToChineseWord = "十七"
ElseIf (number = 18) Then
    noToChineseWord = "十八"
ElseIf (number = 19) Then
    noToChineseWord = "十九"
ElseIf (number = 20) Then
    noToChineseWord = "二十"
ElseIf (number = 21) Then
    noToChineseWord = "二十一"
ElseIf (number = 22) Then
    noToChineseWo3rd = "二十二"
ElseIf (number = 23) Then
    noToChineseWord = "二十三"
ElseIf (number = 24) Then
    noToChineseWord = "二十四"
ElseIf (number = 25) Then
    noToChineseWord = "二十五"
ElseIf (number = 26) Then
    noToChineseWord = "二十六"
ElseIf (number = 27) Then
    noToChineseWord = "二十七"
ElseIf (number = 28) Then
    noToChineseWord = "二十八"
ElseIf (number = 29) Then
    noToChineseWord = "二十九"
ElseIf (number = 30) Then
    noToChineseWord = "三十"
End Function
